### ISSUE TITLE
Suggestion:  Context auto-rotate

### ISSUE THREAD

**Issue by tlhackque** [fwenzel/imagetwist#5]
You have view image opening the image auto-rotated per the EXIF data.

Why not have a (the first?) rotate context menu entry that does the same in place?
Say, rotate ->
   Auto
   CW
   CCW
   180
E.g. the same as the current rotate->xxx, where xxx is what the EXIF data says.  (Note that the EXIF has more choices than the simple three you expose, so "auto" could do them all without complicating the UI.)

You could also have a 'restore' (or maybe 'original') to put the image back to the default orientation...

**Comment by fwenzel** [comment]
I like it, thanks! I'll take a look

**Comment by fwenzel** [comment]
Good call that EXIF has more options than rotation. I don't currently do anything about flipping, but it's doable. I'll make that a separate Issue from this one though.

**Comment by fwenzel** [comment]
So the commit above introduces the "auto" point to the menu. I'll need to see about reverting (I'll make that a separate issue as well). Before closing this Issue, I would like to add a notification. _Possibly_ on success even though you can _see_ success so that's probably not necessary. However, if the image has no EXIF data or the data indicates no rotation is necessary, currently the user gets no feedback at all which sucks. I should notify them about that case.

**Comment by tlhackque** [comment]
Thanks for working on this.  Sounds like good progress.

I grok 'revert', but it's a techie term.  Suggest a word like 'restore' or 'original' for comfort of normal people.

I agree that no notification is needed on success.  The other cases you mention could do with something.

Thanks again.
